// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ErpAPI.Models;

public partial class Banco
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public virtual ICollection<Conta> Conta { get; set; } = new List<Conta>();
}