// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ErpAPI.Models;

public partial class Conta
{
    public int Numero { get; set; }

    public int IdEmpresa { get; set; }

    public int IdBanco { get; set; }

    public virtual Banco IdBancoNavigation { get; set; }

    public virtual Empresa IdEmpresaNavigation { get; set; }
}