// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ErpAPI.Models;

public partial class Funcionario
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Cargo { get; set; }

    public int IdEmpresa { get; set; }

    public virtual ICollection<FuncionarioXprojeto> FuncionarioXprojetos { get; set; } = new List<FuncionarioXprojeto>();

    public virtual Empresa IdEmpresaNavigation { get; set; }
}