// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ErpAPI.Models;

public partial class Pais
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public virtual ICollection<Empresa> Empresas { get; set; } = new List<Empresa>();

    public virtual ICollection<Moeda> Moeda { get; set; } = new List<Moeda>();
}