// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ErpAPI.Models;

public partial class Projeto
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public DateOnly Inicio { get; set; }

    public DateOnly Fim { get; set; }

    public bool Status { get; set; }

    public int IdCliente { get; set; }

    public virtual ICollection<FuncionarioXprojeto> FuncionarioXprojetos { get; set; } = new List<FuncionarioXprojeto>();

    public virtual Cliente IdClienteNavigation { get; set; }
}